apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Sofoniasm/swen-project-.git'
    targetRevision: main
    path: infra/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
